development:
      host: localhost
      adapter: mysql
      database: telm
      port: 3306
      username: root
      password: mysql

test: &test
      host: localhost
      adapter: mysql
      database: telm_test
      port: 3306
      username: root
      password: mysql

production:
      host: localhost
      adapter: mysql
      database: telm
      port: 3306
      username: root
      password: mysql
cucumber:
  <<: *test
